import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  BsFillMoonStarsFill,
  BsFillSunFill,
  BsStackOverflow,
} from "react-icons/bs";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import deved from "../public/profile-picture.jpg";
import ecommerce from "../public/clientside-converter.png";
import jobportal from "../public/elitejobs.png";

import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Vinula Senarathne Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="google-site-verification"
          content="HcgK_lcbSY78O2COJWDv7H_jBAEzPgIlv2JrMDPdeRM"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">vinulasen</h1>
            <ul className="flex items-center">
              <li>
                {!darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl "
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl dark:text-white"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="CV.pdf"
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Vinula Senarathne
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Full Stack Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              Born in 2000 in Colombo, Sri Lanka. I believe web development can
              be more diverse and inspiring. With the new invensions of
              technology, I am pursuing new expressions in the industry.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://twitter.com/vinulapc">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/vinula-senarathne-6b4a301a8">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/vinulays">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={deved}
              alt="3d-rendered-image"
              fill
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
              style={{ objectFit: "cover" }}
            />
          </div>
        </section>

        <section className="mt-16">
          <div className="py-2 text-center">
            <h3 className="text-3xl py-1 dark:text-white">My Portfolio</h3>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="dark:text-white">
              <div className="text-2xl mb-7">
                Client-side Video Converter Application
              </div>
              <a
                href="https://convertify-vinulays.vercel.app"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={ecommerce}
                  alt="web1"
                  className="rounded-lg object-cover"
                />
              </a>
            </div>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="dark:text-white">
              <div className="text-2xl mb-7">
                Elite Jobs - Job portal web application
              </div>
              <a
                href="https://convertify-vinulays.vercel.app"
                target="_blank"
                rel="noreferrer"
              >
                <Image
                  src={jobportal}
                  alt="web2"
                  sizes="(max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  33vw"
                  className="rounded-lg"
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
