import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  BsFillMoonStarsFill,
  BsFillSunFill,
  BsStackOverflow,
} from "react-icons/bs";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import coding from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Vinula Senarathne Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="google-site-verification" content="HcgK_lcbSY78O2COJWDv7H_jBAEzPgIlv2JrMDPdeRM" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">vinulasen</h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl dark:text-white"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className="cursor-pointer text-2xl "
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="CV.pdf"
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Vinula Senarathne
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400">
              Born in 2000 in Colombo, Sri Lanka. I believe web development can
              be more diverse and inspiring. With the new invensions of
              technology, I am pursuing new expressions in the industry.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://twitter.com/vinulapc">
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/vinula-senarathne-6b4a301a8">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/vinulays">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={deved}
              alt="3d-rendered-image"
              fill
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
              style={{ objectFit: "cover" }}
            />
          </div>
        </section>

        <section>
          <div className="my-10">
            <h3 className="text-3xl py-1 dark:text-white">What I do</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque
              labore ratione reiciendis eius voluptatum, cum dolores voluptate
              deserunt tempore. Doloremque dolore commodi quae pariatur et
              quisquam officia. Animi, iure repudiandae?
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image
                className="mx-auto"
                src={design}
                alt="design"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-gray-200">
                Creating elegant designs suited for your best design theory
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Photoshop
              </button>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Figma
              </button>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image
                className="mx-auto"
                src={coding}
                alt="code"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100">
                Quality Code
              </h3>
              <p className="py-2 dark:text-gray-200">
                Creating elegant designs suited for your best design theory
              </p>
              <h4 className="py-4 text-teal-600">Skills I have</h4>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Java
              </button>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                React JS
              </button>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Angular
              </button>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                JavaScript & TypeScript
              </button>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Spring Boot
              </button>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Tailwind CSS
              </button>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image
                className="mx-auto"
                src={consulting}
                alt="consulting"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-100">
                Mentoring
              </h3>
              <p className="py-2 dark:text-gray-200">
                Creating elegant designs suited for your best design theory
              </p>
              <h4 className="py-4 text-teal-600">What I do</h4>
              <button className="px-2 py-1 m-1 dark:text-gray-200 rounded border">
                Roadmapping
              </button>
            </div>
          </div>
        </section>

        <section>
          <div className="py-2">
            <h3 className="text-3xl py-1 dark:text-white">My Projects</h3>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web1"
                className="rounded-lg object-cover"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web2"
                className="rounded-lg object-cover"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web3"
                className="rounded-lg object-cover"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="web4"
                className="rounded-lg object-cover"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="web5"
                className="rounded-lg object-cover"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="web6"
                className="rounded-lg object-cover"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
